kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  selfLink: /api/v1/namespaces/openshift-monitoring/configmaps/cluster-monitoring-config
  uid: 6ae43543-1850-4324-b8cd-0c43c5b717f0
  resourceVersion: '6680737'
  creationTimestamp: '2020-06-29T12:59:48Z'
data:
  config.yaml: |
    prometheusK8s:
      retention: 24h
      volumeClaimTemplate:
        metadata:
          name: prom-pvc
        spec:
          resources:
            accessModes:
              - ReadWriteMany
            requests:
              storage: 10Gi
    alertmanagerMain:
      retention: 24h
      volumeClaimTemplate:
        metadata:
          name: nfs1
        spec:
          resources:
          resources:
            accessModes:
              - ReadWriteMany
            requests:
              storage: 10Gi
